### ISSUE TITLE
doc: Add documentation about canvas internals

### ISSUE THREAD

**Issue by jneug** [cetz-package/cetz#132]
It would be great to extend the manual with developer notes like a description of all keys element dictionaries can take (e.g. `custom-anchors` and `transform-coordinates`).

I went through the known packages using CeTZ and most seem to use the functions provided by `draw.typ`. With CeTZ getting more complex and developers creating new packages on top of it, it might be useful to know about the details to provide custom elements with custom anchors and their own style root.

**Comment by johannes-wolf** [comment]
Style resolve and coordinate resolve got added to the docs with #220.
