### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by fenjalien** [cetz-package/cetz#472]
Instead of (or as well as) writing a pdf manual we should have documentation on a website. Ideally this would be hosted through github pages and be generated from the current docstrings we have.

Some options to use:
- [typst-book](https://github.com/Myriad-Dreamin/typst-book)
  - @johannes-wolf has tested it but it does not seem stable enough
- [mdBook](https://rust-lang.github.io/mdBook/)
  - From a quick glance this might be the best option if we mix it with pandoc. It allows the running of preprocessors so examples could be generated automatically.
- [readthedocs](https://docs.readthedocs.io/en/stable/)

**Comment by johannes-wolf** [comment]
I guess we should give typst-book another try, as the last test was some time ago and as far as I know the performance has improved.

**Comment by Enivex** [comment]
Maybe @Myriad-Dreamin can give some input

**Comment by fenjalien** [comment]
Probably should have updated this sooner but a documentation site is setup! Well at least the infrastructure/site is, the actual content and stuff still need to be moved over to it.

It uses mdbook with a custom preprocessor that adds rendered examples, type pills like the Typst docs, and parameter defintions like we use in the manual.

You can find it here: https://cetz-package.github.io/docs/
