### ISSUE TITLE
Panics when copying anchors from a group with a named element with no default anchor

### ISSUE THREAD

**Issue by fenjalien** [cetz-package/cetz#538]
CeTZ 0.2.1 (Typst 0.11.0) panics with the following code
```
group(name: "a", {
  group(name: "b", {
    line((), (1,1), name: "l")
  })
  copy-anchors("b")
})
```
`"Anchor 'default' not in anchors () for element 'l'"`

The behaviour how `copy-anchors` acutally copies the anchors should change, I'm not sure how right now though.

**Comment by johannes-wolf** [comment]
I think we can give `copy-anchor` a mandatory list of anchor names and make it a shortcut for `for name in (...) { anchor(name, "<elem...>" + name) }`. Since you can now access nested anchors, the problem `copy-anchors` was targeting is solved.
