### ISSUE TITLE
Default value of `shorten-to`

### ISSUE THREAD

**Issue by samuzora** [cetz-package/cetz#543]
Hi! Thanks for the amazing package!

Just a small bug/discrepancy I noticed between docs and implementation of marks. In the docs, it's stated that the default value for `shorten-to` parameter is `none` (which I believe is the intended implementation), however in [here](https://github.com/cetz-package/cetz/blob/3562d65ee239342507039c2dbdd599231428cbf8/src/mark.typ#L32) the default value is set to `auto`.

MWE:

```
#cetz.canvas({
  import cetz.draw: *
  line((0, 1), (5, 1))
  line((0, 0), (5, 0), mark: (symbol: ">", pos: 50%))
})
```

![image](https://github.com/cetz-package/cetz/assets/57425222/5dd8febf-d573-42fb-b132-bde999e115f0)

**Comment by johannes-wolf** [comment]
The default value of `auto` is the intended one, I've added it to the documentation.
