### ISSUE TITLE
Add sawtooth support for plots

### ISSUE THREAD

**Issue by Kees-van-Beilen** [cetz-package/cetz#545]
In the Netherlands when the x and or y axis do not start at zero, one would insert a sawtooth on the axis as in the picture below.
![image](https://github.com/cetz-package/cetz/assets/76178905/94199c80-9a03-4f9a-93b6-41778576e900)

Could someone please add this, or point me to where I could add this change myself

**Comment by johannes-wolf** [comment]
I've added an implementation that allows adding those "break-points" yourself, which can produce the following output:
![grafik](https://github.com/cetz-package/cetz/assets/519002/c5c69ba1-2b33-4f5b-86d1-146b9a452315)

It allows specifying an axis inset (along the axis spine) and placing zig-zag break-points on an axis at a specified position.

The PR is here: #546
Do you have an idea for an API how this should be set up?

**Comment by johannes-wolf** [comment]
*Update:* I've added `x-break: true`, to enable the break for the x-axis _if_ the axis min-value is > 0 (same for the y-axis).
Is this good enough?

In the future, I would like to support broken axes + showing ticks for multiple axes on one side of a plot, but this requires some rewrite of the axes library.
