### ISSUE TITLE
Tick marks extend into west and south axis marks

### ISSUE THREAD

**Issue by kdog3682** [cetz-package/cetz#549]
Here is an example: https://typst.app/project/wOW6Fsiienacud9LUO0tpV

While the north and east stealth arrows look good, the south and west ones, kind of overlap with the tickmark.

**Comment by johannes-wolf** [comment]
Solution: Extend the axes by setting their `padding: .5` style.
The positive extra padding is controlled via `overshoot: <number>`, which only extends in the positive x/y direction. If you set `padding`, you should set `overshoot: 0` to remove the extra padding.
