### ISSUE TITLE
Error bars?

### ISSUE THREAD

**Issue by dantechguy** [cetz-package/cetz#573]
I've looked but I can't find any reference for how to add error bars to column charts?

To be concrete, I mean like this:
![image](https://github.com/cetz-package/cetz/assets/30006489/94890744-aa1b-466b-af55-63ba97340e8a)

If there is a quick and easy fix I can apply that would be great (dissertation due quite soon!). Thanks for your help!

**Comment by johannes-wolf** [comment]
Is using a local clone of cetz an option? If so, I can create a PR that adds that feature and you can use that branch.

**Comment by dantechguy** [comment]
@johannes-wolf I'm using the Typst CLI so I presume so! That would be tremendously useful, thank you so so much!

Purely curious: is there a reason you couldn't merge the PR into the live package? I imagine many people would find it useful! :)

**Comment by johannes-wolf** [comment]
Do you need this feature in combination with clustered charts, though?

**Comment by dantechguy** [comment]
For this specific case, yes I was using clustered charts. However, it is possible I'll need them for other types of graphs, such as line graphs and scatter graphs. My (unqualified) best idea would be a 'draw error bar' function in the 'plot' library, and then each of the relevant graphs in the 'charts' library has access to an error bar parameter which internally calls this 'draw error bar' function, allowing for a more automatic version of it.

Really appreciate your help :)

**Comment by johannes-wolf** [comment]
Ok. The PR is ready to be tested. I've added a `error-key:` argument to both chart elements + the `plot.add-bar` function. You have to pass the key (int or string) to access the error data of your data-rows (like with `label-key` and `value-key`).

**Comment by dantechguy** [comment]
@johannes-wolf Just tried it and it's awesome! Thank you so much <3 Dissertation saved😆
