### ISSUE TITLE
braces degenerate with high amplitudes

### ISSUE THREAD

**Issue by raphCode** [cetz-package/cetz#577]
High aspect ratios of braces, that is high amplitudes with low span values, create some weird shapes.
Not sure if that is too much asked from cetz, but it just seemed to me that `cetz.decorations.braces` should draw nice braces in many situations. I am not really sure what I expect exactly, but I think that raising the amplitude should not drastically change the shape.
![image](https://github.com/cetz-package/cetz/assets/15750438/9a3c7e9f-0702-4287-83c5-73a64b83b4be)

```typst
#import "@preview/cetz:0.2.2"

#set page(height: auto, width: auto)
#set text(15pt)

#cetz.canvas(debug: false, {
  import cetz.draw: *

  let y = 0
  for amp in range(1, 5) {
    for deg in range(4) {
      let start = (deg * 6, y)
      let pointi = 30deg * deg
      cetz.decorations.brace(
        start,
        (rel: (x: 5), to: start),
        amplitude: amp,
        pointiness: pointi,
        outer-pointiness: 90deg,
      )
      if amp == 1 {
        content((2.5 + deg * 6, -0.3), [pointiness: #pointi], anchor: "north")
      }
    }
    content((0, y + 0.3), [amplitude: #amp], anchor: "south")
    y += amp
  }
})
```

**Comment by Enivex** [comment]
Isn't this just a case of operating outside the region of reasonable parameter values?
