### ISSUE TITLE
transformation of named coordinate in specific angles fails

### ISSUE THREAD

**Issue by yagshi** [cetz-package/cetz#580]
There are **some specific angles** (e.g. around 70 deg) that cause strange transformation results.

The example code is here.

```typst
#import "@preview/cetz:0.2.2"

#cetz.canvas({
    import cetz.draw: *
    for i in range(0, 360, step: 10) {
	let th = 1deg * i
	set-ctx(ctx => {
	    ctx.transform = (
		(calc.cos(th), -calc.sin(th), 0, 0),
		(-calc.sin(th), -calc.cos(th), 0, 0),
		(0, 0, 0, 0),
		(0, 0, 0, 1),
	    )
	    return ctx
	})
	circle((0deg, 5), radius: 0.1, name: "X", fill: luma(200))
	line("X", (rel: (2,0)))
	content((), [#th])
    }
})
```
After compilation with Typst 0.10.0 (cf2f789c), I've got the attached result.
![cetzerror](https://github.com/cetz-package/cetz/assets/2875122/afc46bfd-4d4e-4d49-a592-5ad6dcac99f8)

**Comment by johannes-wolf** [comment]
Those are due to rounding errors accumulating when doing the transformations.

**Comment by johannes-wolf** [comment]
Update: The issue is the reverse transform that takes place after finding the intersection.

**Comment by johannes-wolf** [comment]
Fix is ready :)

**Comment by yagshi** [comment]
Thank you for the workaround and fixes!  I'll try it and I'm looking forward your fixes to be pulled.
