### ISSUE TITLE
`draw.content` seems to break `rotate(reflow: true)`

### ISSUE THREAD

**Issue by Jollywatt** [cetz-package/cetz#604]
This is better shown than explained:
```typ
#import "@preview/cetz:0.2.2"

#let obj = rect(rotate(30deg, reflow: true)[hello])

#obj

#cetz.canvas({
  cetz.draw.content(
    (0,0),
    obj
  )
})
```
<img width="252" alt="Screenshot 2024-05-24 at 00 01 57" src="https://github.com/cetz-package/cetz/assets/24970860/88aceea6-b6ac-4163-b59c-5bf8a80d1483">

I assume we expect the both the bare `obj` and the `obj` drawn in a cetz canvas to be the same. (Unless I am mistaken, and this is a result of some styles being applied within `cetz.canvas`?) Either way, it beats me...

**Comment by Jollywatt** [comment]
Update: I think this is an issue with `rotate(reflow: true)` and `measure()` (mis)interacting:
```typ
#set rect(inset: 0pt, stroke: red)

#let obj = rotate(30deg, reflow: true)[hello]

#rect(obj)

#context rect(
  width: measure(obj).width,
  height: measure(obj).height,
  obj,
)
```
<img width="191" alt="Screenshot 2024-05-24 at 00 44 06" src="https://github.com/cetz-package/cetz/assets/24970860/6b25a863-3577-4512-a44e-d401a9f73a58">
I would assume these results should match.

@laurmaedje is this an issue for the Typst compiler?

**Comment by laurmaedje** [comment]
This doesn't look ideal indeed. You can open an issue.

**Comment by johannes-wolf** [comment]
@Jollywatt: You can use `content`'s `angle: <angle>` for rotating cetz content.

**Comment by johannes-wolf** [comment]
Closing this, as it is not a cetz issue.
