### ISSUE TITLE
Add a "no bounds" option for elements so they don't affect layout

### ISSUE THREAD

**Issue by Jollywatt** [cetz-package/cetz#619]
As I understand, bounding boxes always reshape to the drawables they contain, without there being a way for certain drawables to opt-out.

It would be good to have a `bounds: none` option or a `draw.no-bounds(body)` wrapper that sets the drawable's bounds to `none` so it does not affect parent bounds. (A better name for this wrapper might be `draw.place(body)`, or `draw.float(body)`. It would complement `draw.hide(body)` in a sense.)

An example use case is something like in the image below, where it is desired that the canvas bounding box be at the red border, not affected by the long label (a `draw.content` node).

<img width="335" alt="Screenshot 2024-06-01 at 15 07 48" src="https://github.com/cetz-package/cetz/assets/24970860/3785ea53-223d-4df4-80ba-8a5175596405">

**Comment by johannes-wolf** [comment]
Adding something like this is planned. I think `float` is a good name :+1:.
