### ISSUE TITLE
Cannot get plot example to work

### ISSUE THREAD

**Issue by sittim** [cetz-package/cetz#651]
Plot example here:

https://github.com/cetz-package/cetz/blob/master/gallery/plot.typ

does not compile, I get this:

```
error: unknown variable: cetz
  ┌─ test.typ:8:9
  │
8 │   import cetz.plot
  │          ^^^^
```

But, the code linked below works fine, this makes it a bit confusing:

https://raw.githubusercontent.com/typst/packages/main/packages/preview/cetz/0.2.2/gallery/plot.typ

**Comment by fenjalien** [comment]
We're in the process of moving the plotting library to its own package here: https://github.com/cetz-package/cetz-plot. Its not yet been submitted to Typst Universe so it won't be in the `preview` namespace for a while. Please refer to the `0.2.2` tagged example as you have shared.

**Comment by johannes-wolf** [comment]
Sorry, this is because plotting was moved out of cetz but is not yet released as a standalone package in the Typst packages repo.

The line `#import "@preview/cetz-plot:0.1.0": plot` tries importing `cetz-plot` which is not there.

Removing the import and adjusting the cetz import allows compilation:
```typst
#import "@preview/cetz:0.2.2": canvas, plot // add ", plot" here
//#import "@preview/cetz-plot:0.1.0": plot  // Remove this

#set page(width: auto, height: auto, margin: .5cm)

#let style = (stroke: black, fill: rgb(0, 0, 200, 75))

#canvas(length: 1cm, {
  plot.plot(size: (8, 6),
    x-tick-step: none,
    x-ticks: ((-calc.pi, $-pi$), (0, $0$), (calc.pi, $pi$)),
    y-tick-step: 1,
    {
      plot.add(
        style: style,
        domain: (-calc.pi, calc.pi), calc.sin)
      plot.add(
        hypograph: true,
        style: style,
        domain: (-calc.pi, calc.pi), calc.cos)
      plot.add(
        hypograph: true,
        style: style,
        domain: (-calc.pi, calc.pi), x => calc.cos(x + calc.pi))
    })
})
```
