### ISSUE TITLE
Functions become less smooth on larger domain

### ISSUE THREAD

**Issue by Mackevv** [cetz-package/cetz#663]
I don't know if I'm just not using the library correctly but, whenever I try to plot a function like sin on a larger domain like [-15, 15], the curves become less smooth.

![screenshot-20240804-142231](https://github.com/user-attachments/assets/a0fc5444-0dff-4fc5-bf2a-261d3f31f412)
```typst
#canvas({
  plot.plot(
    size: (10, 3),
    axis-style: "school-book",
    x-tick-step: none,
    y-tick-step: none,
    {
      plot.add(domain: (-15, 15), x => calc.sin(x))
    }
  )
})
```

The same thing also happens when I want to represent the behavior of a function when x is approaching zero like sin(1/x) : 

![screenshot-20240804-142735](https://github.com/user-attachments/assets/a512de16-d588-4306-abf3-3ac6f715434f)

```typst
#canvas({
  plot.plot(
    size: (10, 3),
    axis-style: "school-book",
    x-tick-step: 1,
    y-tick-step: 1,
    {
      plot.add(domain: (1e-12, 2), x => calc.sin(1/x)) 
    }
  )
})
```

when it should more look like this

![screenshot-20240804-142858](https://github.com/user-attachments/assets/0aacf1b8-73b7-420b-bb42-e2d9853e96e6)

**Comment by johannes-wolf** [comment]
The number of samples taken from the function is constant and does not depend on the domain. You can increase it with the `samples: <int>` argument of `add()`.

**Comment by johannes-wolf** [comment]
For your second example, you can add additional sampling points by giving `add` a list of those: `sample-at: (..range(0, 500).map(t => 1e-12 + 0.1 * t/500))`. But I guess this is not really a good solution.

**Comment by Mackevv** [comment]
Thank you for your help I didn't know we could do that. For the second example it looks good if I add enough sampling points and decrease the curve thickness so it's okay.
