### ISSUE TITLE
angle results are hard to predict and control

### ISSUE THREAD

**Issue by knuesel** [cetz-package/cetz#712]
The `angle` API is a bit tricky to use in programmatic drawing, where the angle value is not known statically. One must play with `inner` and `mark` to get the right result depending on the angle value. For example I often need figures for different trigonometric angles:

```typ
#let trig-angle(alpha) = cetz.canvas(length: 2cm, {
  import cetz.draw: *

  let O = (0, 0)
  let P = (1, 0)
  let Q = (alpha, 1)

  line(O, P, mark: (end: ">"))
  line(O, Q, mark: (end: ">"))
  cetz.angle.angle(O, P, Q, mark: (end: ">"), label: [#alpha], label-radius: 150%)
  rect((-1, 0), (1, 0), stroke: none) // for bounding box
})

#for alpha in (60deg, 240deg, -60deg, -240deg) {
  box(trig-angle(alpha))
}
```

![image](https://github.com/user-attachments/assets/92286894-e8e1-4583-b431-aba5ffd45426)

The first drawing (60deg) is what I expected, but the others all require different fixes:

* For 240deg I need `inner: false`
* For -60deg I must replace `end: ">"` with `start: ">"`
* For -240deg I need both of the above

(Here I could implement the four cases with conditional logic, but in general the angle can be specified by all sorts of coordinates with no explicit angle value.)

What would you think of the following changes to the API:

* make `angle(O, A, B)` always draw from OA to OB (this makes the effect of mark `start` and `end` more predictable)

* allow `inner: auto`, in which case the angle is drawn counterclockwise for positive values, and clockwise for negative values (I think this should be the default, but having this opt-in would be fine)

**Comment by johannes-wolf** [comment]
I've created a PR #729. Could you please validate that it fulfils your expectations.

**Comment by knuesel** [comment]
(By negative angle I meant clockwise, but then indeed the whole sentence doesn't make sense, sorry! But I'll elaborate in the PR comments)
