### ISSUE TITLE
Update library to use `context` expressions

### ISSUE THREAD

**Issue by aaron-jack-manning** [cetz-package/cetz#720]
Calling functions like `style`, or `measure` with a styles argument, are deprecated in the `0.12.0` release candidate in favor of [context expressions](https://typst.app/docs/reference/context/) and thus produce warnings in `0.12.0`. Since context expressions were introduced as the preferred alternative in `0.11.0`, and cetz `0.3.0` depends on `0.11.0`, implementing this change would not break anything and would prevent the warnings when `0.12.0` releases.

I am happy to make a PR for this.

**Comment by johannes-wolf** [comment]
Cetz 0.3.0 already uses `context` expression. If you find any warnings to it, feel free to open up a PR, but last time I checked, I could not find any use of the deprecated ways of calling `style` or `measure`.

**Comment by aaron-jack-manning** [comment]
You're so right! Sorry, I thought I upgraded but it was through a transitive dependency on the old version.
