### ISSUE TITLE
Regression in content alignment

### ISSUE THREAD

**Issue by lacarthur** [cetz-package/cetz#721]
Hello, I have an issue with content alignment in the new 0.3.0 version.
When compiling the following code: 
```typst
#cetz.canvas({
  import cetz.draw: *

  let elements = ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l")

  line((1, 4), (13, 4), (13, 3), (1, 3), close: true)

  for i in range(1, 13) {
    line((i, 4), (i, 3))
    content((i + 0.5, 3.5), [#elements.at(i - 1)])
  }
})
```
The images produced are different in 0.2.2 and 0.3.0:

This is 0.2.2: 
![version0 2 2](https://github.com/user-attachments/assets/20606216-d5ea-4c34-8c43-12affa728c7d)

and this is 0.3.0:
![version0 3 0](https://github.com/user-attachments/assets/8ebdc55f-d001-41e5-a843-63565f3ac9fd)
The smaller letters dip below the larger letters. Is this some new default behaviour that I haven't seen in the changelog, or is this actually a regression?

**Comment by johannes-wolf** [comment]
Fixed with #717

**Comment by fenjalien** [comment]
#717 was merged can this be closed?

**Comment by johannes-wolf** [comment]
Workaround for 0.3.0: Wrap text in `text(top-edge: "ascender", bottom-edge: "baseline", [...])`
