### ISSUE TITLE
Mark positioning with anchor

### ISSUE THREAD

**Issue by arkadiuszwojcik** [cetz-package/cetz#723]
First of all thank you all for you work on this awesome library!
I am testing 0.3.0 release now and new mark positioning feature: `anchor: "center"`. This is my code:

```
#cetz.canvas({
  import cetz.draw: *

  circle((-1, 0), radius: 0.02, fill: black, name: "a")
  circle(( 1, 0), radius: 0.02, fill: black, name: "b")
   
  line("a.center", "b.center")
  mark("a.center", "b.center", symbol: "<", fill: black, anchor: "center")
  mark("b.center", "a.center", symbol: "<", fill: black, anchor: "center")

  circle((-1, -1), radius: 0.02, fill: black, name: "c")
  circle(( 1, -1), radius: 0.02, fill: black, name: "d")

  line("c.center", "d.center")
  mark("c.center", "d.center", symbol: ">", fill: black, anchor: "center")
  mark("d.center", "c.center", symbol: ">", fill: black, anchor: "center")
})
```

and this is the result:

![Screenshot 2024-10-17 205716](https://github.com/user-attachments/assets/21832a38-8fa5-4cf7-ba9f-ee4e64028a44)

The bottom line that use `>` marks looks exactly as I would expect. But top one with `<` marks looks strange. I would expect arrow/marks heds to be in same position like on bottom example but pointing opposite direction. Is it a bug or I am using it wrong way?

**Comment by johannes-wolf** [comment]
There seems to be a bug with reversed marks `(reverse: true)` and their anchors.
