### ISSUE TITLE
Lines between contents do not work properly in 0.3

### ISSUE THREAD

**Issue by TimotheAlbouy** [cetz-package/cetz#753]
In cetz 0.3, when we draw a line between two contents, the line starts from the center of the content instead of the edge of the content.

```
#import "@preview/cetz:0.3.1": canvas, draw

#canvas({
  import draw: *
  
  content((0, 0), [Content 1], name: "C1")
  content((4, 0), [Content 2], name: "C2")
  line("C1", "C2")
})
```

![image](https://github.com/user-attachments/assets/c9f053f4-5c27-4361-9e9e-bc42595e09fc)

This is a regression as this worked properly in cetz 0.2.

```
#import "@preview/cetz:0.2.2": canvas, draw

#canvas({
  import draw: *
  
  content((0, 0), [Content 1], name: "C1")
  content((4, 0), [Content 2], name: "C2")
  line("C1", "C2")
})
```

![image](https://github.com/user-attachments/assets/27649bff-b01c-4e0f-af8a-0c905a93e012)

**Comment by johannes-wolf** [comment]
Question is, if `content` should have a default frame `"rect"` that is invisible by default.

**Comment by TimotheAlbouy** [comment]
In cetz 0.2 content had an implicity "rect" frame? Then IMHO, cetz 0.3 should also have that. The simplicity of having `line("C1", "C2")` work directly without having to specify an invisible frame was really convenient in 0.2.
