### ISSUE TITLE
Build a polygon from lines and bezier curves

### ISSUE THREAD

**Issue by manuelVo** [cetz-package/cetz#770]
I'd like to draw a complex arrow that looks like this:

![An arrow splitting up into multiple curved sub-arrows pointing into different directions](https://github.com/user-attachments/assets/80c66edf-8c43-4b64-a031-3f9b948a6db8)

Ultimately, this shape is a series of lines (and bezier curves) that is closed to be able to fill it. However, this currently seems impossible (or at least hard) to do in cetz, as it appears `line` doesn't support control points for bezier curves and `bezier` doesn't support joining multiple curves into a closed shape.

I'd like to ask for a feature to combine the two. One possible interface for this could be similar to the typst [`path` function](https://typst.app/docs/reference/visualize/path/) where control points can be optionally passed as part of the vertices.

**Comment by johannes-wolf** [comment]
This is possible. You can join multiple `line`s and `bezier` curves via `merge-path({ .. elements .. })`.

**Comment by manuelVo** [comment]
This works great, thanks!
