### ISSUE TITLE
Inconsistent anchor calculation for groups of asymmetric size between using the anchor as `anchor` parameter or in a relative coordinate

### ISSUE THREAD

**Issue by manuelVo** [cetz-package/cetz#772]
When using the anchors of a group that has an asymmetric size (i.e. the origin is not in the center of the group), the anchor calculation for that group is inconsistent. Depending on where the anchor is being used (as the `anchor` parameter for the group or as part of a relative coordinate), different coordinates end up being calculated.

Example: The following code

```typst
#import "@preview/cetz:0.3.1"

#cetz.canvas({
  import cetz.draw: *

  let asymmetric_group(pos, text, anchor: none, name: none) = {
    group(
      name: name,
      anchor: anchor,
      get-ctx(ctx => {
        let (ctx, pos) = cetz.coordinate.resolve(ctx, pos)
        set-origin(pos)
        rect((-1cm, 0cm), (2cm,2cm))
      })
    )
  }
  
  content((1, 1cm), name: "north1", "North1")
  asymmetric_group((rel: (0,0), to: "north1"), anchor: "north", name: "group", "Some text")
  content((rel: (0,0), to: "group.north"), "North2")
})
```
uses the `north` anchor of the group twice. Once when defining the group to determine that the group shall be anchored at its north side. The second time the anchor is being used as part of the relative position of the second `content` element. Again, this element is placed at the group's north. Since both `content` elements are placed at the group's `north`, i would expect them to be placed at the exact same position. However, the following is what's actually being rendered:

![grafik](https://github.com/user-attachments/assets/4f8a38f8-abd2-431c-8955-503006b0d5fa)

**Comment by johannes-wolf** [comment]
I've tested this. This is not a bug. The documentation specifies how the group anchor works:
You have to set an anchor called `"default"` as the groups origin (`anchor("default", pos)` in your case).
